import { enumsType, keyValueProp } from '../types/index';
export const OTHER = 'other';

/**
 * engine引擎类型
 */
export const engineEnums: keyValueProp[] = [
  { key: 'AppleWebKit', value: 'WebKit' },
  { key: ['NET CLR', 'Trident'], value: 'Trident' },
  { key: 'Gecko/', value: 'Gecko' },
  { key: 'Presto', value: 'Presto' }
]

/**
 * browser浏览器类型
 */
export const browserEnums: keyValueProp[] = [
  { key: 'Safari', value: 'Safari' },
  { key: ['CriOS', 'Chrome'], value: 'Chrome' },
  { key: ['Edge', 'MSIE'], value: 'Edge' },
  { key: 'Trident', value: 'IE' },
  { key: ['FxiOS', 'Firefox'], value: 'Firefox' },
  { key: 'Focus', value: 'Firefox Focus' },
  { key: 'Chromium', value: 'Chromium' },
  { key: ['Opera', 'OPR'], value: 'Opera' },
  { key: 'Vivaldi', value: 'Vivaldi' },
  { key: 'YaBrowser', value: 'Yandex' },
  { key: 'Arora', value: 'Arora' },
  { key: 'Lunascape', value: 'Lunascape' },
  { key: 'QupZilla', value: 'QupZilla' },
  { key: 'coc_coc_browser', value: 'Coc Coc' },
  { key: 'Iceweasel', value: 'Iceweasel' },
  { key: 'Konqueror', value: 'Konqueror' },
  { key: 'Iceape', value: 'Iceape' },
  { key: ['Kindle', 'Silk/'], value: 'Kindle' },
  { key: 'SeaMonkey', value: 'SeaMonkey' },
  { key: ['QihooBrowser', 'QHBrowser'], value: '360' },
  { key: '360EE', value: '360EE' },
  { key: '360SE', value: '360SE' },
  { key: ['UBrowser', 'UC'], value: 'UC' },
  { key: 'QQBrowser', value: 'QQBrowser' },
  { key: 'QQ/', value: 'QQ' },
  { key: ['Baidu', 'BIDUBrowser'], value: 'Baidu' },
  { key: ['MetaSr', 'Sogou'], value: 'Sogou' },
  { key: '2345Explorer', value: '2345Explorer' },
  { key: 'MiuiBrowser', value: 'XiaoMi' },
  { key: 'Quark', value: 'Quark' },
  { key: 'Qiyu', value: 'Qiyu' },
  { key: 'MicroMessenger', value: 'Wechat' },
  { key: 'AliApp(TB', value: 'Taobao' },
  { key: 'AliApp(AP', value: 'Alipay' },
  { key: 'Weibo', value: 'Weibo' },
  { key: 'com.douban.frodo', value: 'Douban' },
  { key: 'SNEBUY-APP', value: 'Suning' },
  { key: 'IqiyiApp', value: 'iQiYi' }
]

/**
 * 系统类型
 */
export const platformEnums: keyValueProp[] = [
  { key: 'Windows', value: 'Windows' },
  { key: ['Linux', 'X11'], value: 'Linux' },
  { key: 'Macintosh', value: 'Mac OS' },
  { key: ['Android', 'Adr'], value: 'Android' },
  { key: 'Ubuntu', value: 'Ubuntu' },
  { key: 'FreeBSD', value: 'FreeBSD' },
  { key: ['Windows Phone', 'IEMobile'], value: 'Windows Phone' },
  { key: ['BlackBerry', 'RIM'], value: 'BlackBerry' },
  { key: 'MeeGo', value: 'MeeGo' },
  { key: 'like Mac OS X', value: 'iOS' },
  { key: 'CrOS', value: 'Chrome OS' },
  { key: 'hpwOS', value: 'WebOS' },
]

/**
 * 其余设备
 */
export const equipmentEnums: keyValueProp[] = [
  { key: ['Mobi', 'iPh', '480'], value: 'Mobile' },
  { key: ['Tablet', 'Nexus 7'], value: 'Tablet' },
  { key: 'iPad', value: 'iPad' }
]

/**
 * 语言代码表
 */
export const languageEnums: keyValueProp[] = [
  { key: 'af', value: '南非语' },
  { key: 'af-ZA', value: '南非语' },
  { key: 'ar', value: '阿拉伯语' },
  { key: 'ar-AE', value: '阿拉伯语(阿联酋)' },
  { key: 'ar-BH', value: '阿拉伯语(巴林)' },
  { key: 'ar-DZ', value: '阿拉伯语(阿尔及利亚)' },
  { key: 'ar-EG', value: '阿拉伯语(埃及)' },
  { key: 'ar-IQ', value: '阿拉伯语(伊拉克)' },
  { key: 'ar-JO', value: '阿拉伯语(约旦)' },
  { key: 'ar-KW', value: '阿拉伯语(科威特)' },
  { key: 'ar-LB', value: '阿拉伯语(黎巴嫩)' },
  { key: 'ar-LY', value: '阿拉伯语(利比亚)' },
  { key: 'ar-MA', value: '阿拉伯语(摩洛哥)' },
  { key: 'ar-OM', value: '阿拉伯语(阿曼)' },
  { key: 'ar-QA', value: '阿拉伯语(卡塔尔)' },
  { key: 'ar-SA', value: '阿拉伯语(沙特阿拉伯)' },
  { key: 'ar-SY', value: '阿拉伯语(叙利亚)' },
  { key: 'ar-TN', value: '阿拉伯语(突尼斯)' },
  { key: 'ar-YE', value: '阿拉伯语(也门)' },
  { key: 'az', value: '阿塞拜疆语' },
  { key: 'az-AZ', value: '阿塞拜疆语(拉丁文)' },
  { key: 'az-AZ', value: '阿塞拜疆语(西里尔文)' },
  { key: 'be', value: '比利时语' },
  { key: 'be-BY', value: '比利时语' },
  { key: 'bg', value: '保加利亚语' },
  { key: 'bg-BG', value: '保加利亚语' },
  { key: 'bs-BA', value: '波斯尼亚语(拉丁文，波斯尼亚和黑塞哥维那)' },
  { key: 'ca', value: '加泰隆语' },
  { key: 'ca-ES', value: '加泰隆语' },
  { key: 'cs', value: '捷克语' },
  { key: 'cs-CZ', value: '捷克语' },
  { key: 'cy', value: '威尔士语' },
  { key: 'cy-GB', value: '威尔士语' },
  { key: 'da', value: '丹麦语' },
  { key: 'da-DK', value: '丹麦语' },
  { key: 'de', value: '德语' },
  { key: 'de-AT', value: '德语(奥地利)' },
  { key: 'de-CH', value: '德语(瑞士)' },
  { key: 'de-DE', value: '德语(德国)' },
  { key: 'de-LI', value: '德语(列支敦士登)' },
  { key: 'de-LU', value: '德语(卢森堡)' },
  { key: 'dv', value: '第维埃语' },
  { key: 'dv-MV', value: '第维埃语' },
  { key: 'el', value: '希腊语' },
  { key: 'el-GR', value: '希腊语' },
  { key: 'en', value: '英语' },
  { key: 'en-AU', value: '英语(澳大利亚)' },
  { key: 'en-BZ', value: '英语(伯利兹)' },
  { key: 'en-CA', value: '英语(加拿大)' },
  { key: 'en-CB', value: '英语(加勒比海)' },
  { key: 'en-GB', value: '英语(英国)' },
  { key: 'en-IE', value: '英语(爱尔兰)' },
  { key: 'en-JM', value: '英语(牙买加)' },
  { key: 'en-NZ', value: '英语(新西兰)' },
  { key: 'en-PH', value: '英语(菲律宾)' },
  { key: 'en-TT', value: '英语(特立尼达)' },
  { key: 'en-US', value: '英语(美国)' },
  { key: 'en-ZA', value: '英语(南非)' },
  { key: 'en-ZW', value: '英语(津巴布韦)' },
  { key: 'eo', value: '世界语' },
  { key: 'es', value: '西班牙语' },
  { key: 'es-AR', value: '西班牙语(阿根廷)' },
  { key: 'es-BO', value: '西班牙语(玻利维亚)' },
  { key: 'es-CL', value: '西班牙语(智利)' },
  { key: 'es-CO', value: '西班牙语(哥伦比亚)' },
  { key: 'es-CR', value: '西班牙语(哥斯达黎加)' },
  { key: 'es-DO', value: '西班牙语(多米尼加共和国)' },
  { key: 'es-EC', value: '西班牙语(厄瓜多尔)' },
  { key: 'es-ES', value: '西班牙语(传统)' },
  { key: 'es-ES', value: '西班牙语(国际)' },
  { key: 'es-GT', value: '西班牙语(危地马拉)' },
  { key: 'es-HN', value: '西班牙语(洪都拉斯)' },
  { key: 'es-MX', value: '西班牙语(墨西哥)' },
  { key: 'es-NI', value: '西班牙语(尼加拉瓜)' },
  { key: 'es-PA', value: '西班牙语(巴拿马)' },
  { key: 'es-PE', value: '西班牙语(秘鲁)' },
  { key: 'es-PR', value: '西班牙语(波多黎各(美))' },
  { key: 'es-PY', value: '西班牙语(巴拉圭)' },
  { key: 'es-SV', value: '西班牙语(萨尔瓦多)' },
  { key: 'es-UY', value: '西班牙语(乌拉圭)' },
  { key: 'es-VE', value: '西班牙语(委内瑞拉)' },
  { key: 'et', value: '爱沙尼亚语' },
  { key: 'et-EE', value: '爱沙尼亚语' },
  { key: 'eu', value: '巴士克语' },
  { key: 'eu-ES', value: '巴士克语' },
  { key: 'fa', value: '法斯语' },
  { key: 'fa-IR', value: '法斯语' },
  { key: 'fi', value: '芬兰语' },
  { key: 'fi-FI', value: '芬兰语' },
  { key: 'fo', value: '法罗语' },
  { key: 'fo-FO', value: '法罗语' },
  { key: 'fr', value: '法语' },
  { key: 'fr-BE', value: '法语(比利时)' },
  { key: 'fr-CA', value: '法语(加拿大)' },
  { key: 'fr-CH', value: '法语(瑞士)' },
  { key: 'fr-FR', value: '法语(法国)' },
  { key: 'fr-LU', value: '法语(卢森堡)' },
  { key: 'fr-MC', value: '法语(摩纳哥)' },
  { key: 'gl', value: '加里西亚语' },
  { key: 'gl-ES', value: '加里西亚语' },
  { key: 'gu', value: '古吉拉特语' },
  { key: 'gu-IN', value: '古吉拉特语' },
  { key: 'he', value: '希伯来语' },
  { key: 'he-IL', value: '希伯来语' },
  { key: 'hi', value: '印地语' },
  { key: 'hi-IN', value: '印地语' },
  { key: 'hr', value: '克罗地亚语' },
  { key: 'hr-BA', value: '克罗地亚语(波斯尼亚和黑塞哥维那)' },
  { key: 'hr-HR', value: '克罗地亚语' },
  { key: 'hu', value: '匈牙利语' },
  { key: 'hu-HU', value: '匈牙利语' },
  { key: 'hy', value: '亚美尼亚语' },
  { key: 'hy-AM', value: '亚美尼亚语' },
  { key: 'id', value: '印度尼西亚语' },
  { key: 'id-ID', value: '印度尼西亚语' },
  { key: 'is', value: '冰岛语' },
  { key: 'is-IS', value: '冰岛语' },
  { key: 'it', value: '意大利语' },
  { key: 'it-CH', value: '意大利语(瑞士)' },
  { key: 'it-IT', value: '意大利语(意大利)' },
  { key: 'ja', value: '日语' },
  { key: 'ja-JP', value: '日语' },
  { key: 'ka', value: '格鲁吉亚语' },
  { key: 'ka-GE', value: '格鲁吉亚语' },
  { key: 'kk', value: '哈萨克语' },
  { key: 'kk-KZ', value: '哈萨克语' },
  { key: 'kn', value: '卡纳拉语' },
  { key: 'kn-IN', value: '卡纳拉语' },
  { key: 'ko', value: '朝鲜语' },
  { key: 'ko-KR', value: '朝鲜语' },
  { key: 'kok', value: '孔卡尼语' },
  { key: 'kok-IN', value: '孔卡尼语' },
  { key: 'ky', value: '吉尔吉斯语' },
  { key: 'ky-KG', value: '吉尔吉斯语(西里尔文)' },
  { key: 'lt', value: '立陶宛语' },
  { key: 'lt-LT', value: '立陶宛语' },
  { key: 'lv', value: '拉脱维亚语' },
  { key: 'lv-LV', value: '拉脱维亚语' },
  { key: 'mi', value: '毛利语' },
  { key: 'mi-NZ', value: '毛利语' },
  { key: 'mk', value: '马其顿语' },
  { key: 'mk-MK', value: '马其顿语(' },
  { key: 'FYROM', value: ')' },
  { key: 'mn', value: '蒙古语' },
  { key: 'mn-MN', value: '蒙古语(西里尔文)' },
  { key: 'mr', value: '马拉地语' },
  { key: 'mr-IN', value: '马拉地语' },
  { key: 'ms', value: '马来语' },
  { key: 'ms-BN', value: '马来语(文莱达鲁萨兰)' },
  { key: 'ms-MY', value: '马来语(马来西亚)' },
  { key: 'mt', value: '马耳他语' },
  { key: 'mt-MT', value: '马耳他语' },
  { key: 'nb', value: '挪威语(伯克梅尔)' },
  { key: 'nb-NO', value: '挪威语(伯克梅尔)(挪威)' },
  { key: 'nl', value: '荷兰语' },
  { key: 'nl-BE', value: '荷兰语(比利时)' },
  { key: 'nl-NL', value: '荷兰语(荷兰)' },
  { key: 'nn-NO', value: '挪威语(尼诺斯克)(挪威)' },
  { key: 'ns', value: '北梭托语' },
  { key: 'ns-ZA', value: '北梭托语' },
  { key: 'pa', value: '旁遮普语' },
  { key: 'pa-IN', value: '旁遮普语' },
  { key: 'pl', value: '波兰语' },
  { key: 'pl-PL', value: '波兰语' },
  { key: 'pt', value: '葡萄牙语' },
  { key: 'pt-BR', value: '葡萄牙语(巴西)' },
  { key: 'pt-PT', value: '葡萄牙语(葡萄牙)' },
  { key: 'qu', value: '克丘亚语' },
  { key: 'qu-BO', value: '克丘亚语(玻利维亚)' },
  { key: 'qu-EC', value: '克丘亚语(厄瓜多尔)' },
  { key: 'qu-PE', value: '克丘亚语(秘鲁)' },
  { key: 'ro', value: '罗马尼亚语' },
  { key: 'ro-RO', value: '罗马尼亚语' },
  { key: 'ru', value: '俄语' },
  { key: 'ru-RU', value: '俄语' },
  { key: 'sa', value: '梵文' },
  { key: 'sa-IN', value: '梵文' },
  { key: 'se', value: '北萨摩斯语' },
  { key: 'se-FI', value: '北萨摩斯语(芬兰)' },
  { key: 'se-FI', value: '斯科特萨摩斯语(芬兰)' },
  { key: 'se-FI', value: '伊那里萨摩斯语(芬兰)' },
  { key: 'se-NO', value: '北萨摩斯语(挪威)' },
  { key: 'se-NO', value: '律勒欧萨摩斯语(挪威)' },
  { key: 'se-NO', value: '南萨摩斯语(挪威)' },
  { key: 'se-SE', value: '北萨摩斯语(瑞典)' },
  { key: 'se-SE', value: '律勒欧萨摩斯语(瑞典)' },
  { key: 'se-SE', value: '南萨摩斯语(瑞典)' },
  { key: 'sk', value: '斯洛伐克语' },
  { key: 'sk-SK', value: '斯洛伐克语' },
  { key: 'sl', value: '斯洛文尼亚语' },
  { key: 'sl-SI', value: '斯洛文尼亚语' },
  { key: 'sq', value: '阿尔巴尼亚语' },
  { key: 'sq-AL', value: '阿尔巴尼亚语' },
  { key: 'sr-BA', value: '塞尔维亚语(拉丁文，波斯尼亚和黑塞哥维那)' },
  { key: 'sr-BA', value: '塞尔维亚语(西里尔文，波斯尼亚和黑塞哥维那)' },
  { key: 'sr-SP', value: '塞尔维亚(拉丁)' },
  { key: 'sr-SP', value: '塞尔维亚(西里尔文)' },
  { key: 'sv', value: '瑞典语' },
  { key: 'sv-FI', value: '瑞典语(芬兰)' },
  { key: 'sv-SE', value: '瑞典语' },
  { key: 'sw', value: '斯瓦希里语' },
  { key: 'sw-KE', value: '斯瓦希里语' },
  { key: 'syr', value: '叙利亚语' },
  { key: 'syr-SY', value: '叙利亚语' },
  { key: 'ta', value: '泰米尔语' },
  { key: 'ta-IN', value: '泰米尔语' },
  { key: 'te', value: '泰卢固语' },
  { key: 'te-IN', value: '泰卢固语' },
  { key: 'th', value: '泰语' },
  { key: 'th-TH', value: '泰语' },
  { key: 'tl', value: '塔加路语' },
  { key: 'tl-PH', value: '塔加路语(菲律宾)' },
  { key: 'tn', value: '茨瓦纳语' },
  { key: 'tn-ZA', value: '茨瓦纳语' },
  { key: 'tr', value: '土耳其语' },
  { key: 'tr-TR', value: '土耳其语' },
  { key: 'ts', value: '宗加语' },
  { key: 'tt', value: '鞑靼语' },
  { key: 'tt-RU', value: '鞑靼语' },
  { key: 'uk', value: '乌克兰语' },
  { key: 'uk-UA', value: '乌克兰语' },
  { key: 'ur', value: '乌都语' },
  { key: 'ur-PK', value: '乌都语' },
  { key: 'uz', value: '乌兹别克语' },
  { key: 'uz-UZ', value: '乌兹别克语(拉丁文)' },
  { key: 'uz-UZ', value: '乌兹别克语(西里尔文)' },
  { key: 'vi', value: '越南语' },
  { key: 'vi-VN', value: '越南语' },
  { key: 'xh', value: '班图语' },
  { key: 'xh-ZA', value: '班图语' },
  { key: 'zh', value: '中文' },
  { key: 'zh-CN', value: '中文(简体)' },
  { key: 'zh-HK', value: '中文(香港)' },
  { key: 'zh-MO', value: '中文(澳门)' },
  { key: 'zh-SG', value: '中文(新加坡)' },
  { key: 'zh-TW', value: '中文(繁体)' },
  { key: 'zu', value: '祖鲁语' },
  { key: 'zu-ZA', value: '祖鲁语' }
]
